version: '2'

volumes:
    postgres-data:
        driver: local

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
        volumes_from:
            - php
        links:
            - php

    php:
        build: ./docker/php/
        links:
            - postgres
        expose:
            - "9000"
        volumes:
            - ./:/var/www/app/
        working_dir: /var/www/app/
        environment:
            - SYMFONY_ENV=dev
            - PGHOST=postgres
            - DATABASE_DSN=pgsql:host=postgres;port=5432;dbname=techmeetups;user=postgres;password=postgres
        env_file:
            - ./docker/env

    postgres:
        restart: always
        image: postgres:latest
        expose:
            - "5432"
        ports:
            - "5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=techmeetups

    composer:
        restart: 'no'
        image: composer/composer:php7
        command: install
        volumes:
            - .:/app
