services:
    app.meetup_client:
        class: Meetup\Meetup
        factory: ['Meetup\MeetupApiKeyFactory', create]
        arguments: ['']

    app.event_provider.meetup:
        class: Infrastructure\Api\Meetup\EventProvider
        arguments: ['@app.meetup_client']

    app.city_repository:
        class: Infrastructure\Persistence\InMemory\InMemoryCityRepository
        factory: ['Infrastructure\Persistence\InMemory\InMemoryCityRepositoryFactory', create]
        arguments: ['%app.techmeetups.cities%']

    app.city_configuration_repository:
        class: Infrastructure\Persistence\InMemory\InMemoryCityConfigurationRepository
        factory: ['Infrastructure\Persistence\InMemory\InMemoryCityConfigurationRepositoryFactory', create]
        arguments:
            - '@app.city_repository'
            - '%app.techmeetups.cities%'

    app.event_repository:
        class: Infrastructure\Persistence\InMemory\InMemoryEventRepository

    app.event_synchronizer:
        class: Application\Event\Synchronizer
        arguments:
            - "@app.city_configuration_repository"
            - "@app.event_provider.meetup"
            - "@app.event_repository"
            - "@logger"

    app.command.synchronize:
        class: UI\Command\SynchronizeCommand
        arguments: ['@app.event_synchronizer']
        tags:
            - { name: console.command }
